### ISSUE TITLE
A box to preview anonymous question before posting

### ISSUE THREAD

**Issue by a-khaldi** [CMU-17313Q/fall23-nodebb-the-powerpuff-girls#33]
Estimated Effort:

Easy/Medium: There should be box next to the original box that the user is typing in so they could see how their question would look like before submitting.

Acceptance Criteria:

As I am writing my question, I should be able to see a preview next to the box I am currently writing in.

Component #7

**Comment by ssaloos** [comment]
Pop-up message milestone fell through due to being dependant on another feature that led to a delay; moved to Sprint 2.

**Comment by Malika1109** [comment]
This issue has been removed from the sprint 2 planning as we found it created little value to the whole feature. The estimated effort was inaccurate, actual efforts were too high and the impact it was adding was minimal, so we decided not to go ahead with this issue.
